### ISSUE TITLE
Selenium webdriver for Firefox

### ISSUE THREAD

**Issue by lislis** [travis-ci/packer-templates#265] opened 2016-08-23 11:48 UTC
After #imagegaddon and the first round of fixes there is still an issue with the Selenium webdriver for Firefox.

Reported here: https://github.com/travis-ci/travis-cookbooks/pull/742#issuecomment-240686204
And also a customer mentioned it it:
https://secure.helpscout.net/conversation/238063119/33429/?folderId=30784

**Comment by lislis** [comment] 2016-08-23 15:02
This customer reports that their setup with the Selenium FF driver works again, although it is very unstable
https://secure.helpscout.net/conversation/238947086/0/

**Comment by meatballhat** [comment] 2016-09-01 14:59
I'm unable to reproduce the error, and given that the customer is reporting something like success, I'm going to close this out :+1:

**Closed by meatballhat** 2016-09-01 14:59 UTC
Labels: bug
