### ISSUE TITLE
Some tasks try and fail to load kernel module "fglrx" module

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/packer-templates#221] opened 2016-08-10 17:04 UTC
We have two reports of this issue:

https://travis-ci.org/nschloe/mikado/jobs/151069106#L1283-L1285
https://travis-ci.org/nest/nest-simulator/jobs/151195632#L3100-L3102

These jobs are not loading the module explicitly. The issue was either inapplicable before, or the dependencies changed.

**Comment by nschloe** [comment] 2016-08-10 17:20
And another one:

https://travis-ci.org/nschloe/pyfvm/builds/151269557

Might be OpenMPI-related (I see ORTE/MPI in all related builds).

**Comment by jougs** [comment] 2016-08-10 19:01
I am the NEST developer, who reported this. It definitely only happens if we compile with MPI. If you need further information, please feel free to ask.

**Comment by peastman** [comment] 2016-08-13 00:34
I have the same problem: https://travis-ci.org/pandegroup/openmm/jobs/151880210.  In our case, it happens when trying to install the AMD APP SDK.  (We use OpenCL.)

**Comment by meatballhat** [comment] 2016-08-15 00:59
Affected images from above links:
- travis-ci-sugilite-trusty-1470771552
- travis-ci-connie-trusty-1470689286
- travis-ci-sugilite-trusty-1470806235
- travis-ci-sugilite-trusty-1470926354

**Comment by jougs** [comment] 2016-08-15 09:58
I don't think it is related to any specific image as *all* our builds using MPI are failing with this error. The problem is there since about a week. See https://travis-ci.org/nest/nest-simulator/pull_requests for more.

**Comment by gsjaardema** [comment] 2016-08-15 17:05
Also seeing this issue with the mpi-enabled builds on SEACAS project. https://travis-ci.org/gsjaardema/seacas/jobs/152434527

**Comment by meatballhat** [comment] 2016-08-18 16:10
@jougs I could definitely use some help understanding this 😸 

So far I've been able to reproduce the error by forking @gsjaardema's project, confirming that explicit `apt-get install -y fglrx` *does not* remove the error.  I don't understand *why* the kernel module cannot be loaded, and what I'm finding on the interwebs is not so encouraging.  What I *do* know is that having `fglrx` preinstalled on the affected stacks is not an option, as it causes the `GLX` extension to be disabled for virtual framebuffers, although I don't know why that's the case.

**Comment by gsjaardema** [comment] 2016-08-18 19:05
Do we know if the problem is a result of openmpi-bin changing or a result of some change to the travis system?  I am only seeing the issue with mpi and it started 2016-08-09; everything worked 2016-08-08.

**Comment by peastman** [comment] 2016-08-18 19:12
It's definitely a change to travis.  I don't use OpenMPI, but I started getting exactly the same error on the same day when trying to install the AMD APP SDK (which hadn't changed).

**Comment by jougs** [comment] 2016-08-18 20:35
Can you get me shell access to an affected machine? With just the logs at hand I'm quite helpless.

**Comment by meatballhat** [comment] 2016-08-19 03:22
@gsjaardema We (Travis CI) had an [incident on 2016-08-09](https://www.traviscistatus.com/incidents/11hp8bhkrkn7) that required a roll forward to newer-provisioned GCE images, so I think it's safe to assume that there's something in the images we're now using that is different enough from what was previously used that's causing the error(s) you're seeing.

I personally don't understand OpenMPI or its relationship to fglrx enough to figure this out.

@jougs I'll have to spin up a long-lived GCE instance for this, but yep it's possible.  Can you email support@travis-ci.org and CC dan@travis-ci.org to let us know how you'd prefer to receive SSH connection info?

**Comment by nschloe** [comment] 2016-08-22 20:06
@jougs Able to figure out anything?

**Comment by gsjaardema** [comment] 2016-08-22 20:44
My mpi builds started working this weekend.

**Comment by nschloe** [comment] 2016-08-22 21:24
I tried as well and saw the bug fixed on one of my project, but not on [another](https://travis-ci.org/nschloe/pyfvm/builds/153524340).

**Comment by meatballhat** [comment] 2016-08-23 02:10
@gsjaardema oh, weird!  I hadn't come up with anything yet, so afaik this is still broken.  Is it safe to assume that you didn't change anything related on your end, to your knowledge?

**Comment by gsjaardema** [comment] 2016-08-23 12:22
@meatballhat No, i changed nothing that I could see would be related.

**Comment by heplesser** [comment] 2016-08-25 11:02
@meatballhat @jougs I just re-ran all builds that had failed in our repo earlier and all worked fine now.

**Comment by nschloe** [comment] 2016-08-25 15:33
All my tests are passing now too.

**Comment by peastman** [comment] 2016-08-25 15:39
Mine too.  Thanks for whatever you did!

**Comment by meatballhat** [comment] 2016-09-01 15:04
I'm a bit boggled about how or why this was fixed, but I can't really justify researching further if everyone in this thread is reporting success 🎉 😕

**Closed by meatballhat** 2016-09-01 15:04 UTC
Labels: bug, packer/googlecompute, ubuntu/trusty
